# Singular or non singular

1. non_singular ---> (x+y=5)(,x+2y=6)--> y=1,x=4 ==> unique solution
2. singular and redundant ---> (x+y=2),(2x+2y=4)---> many solutions
3. singular and contradiction ---> (x+y=5),(x+y=10)---> !!! no solution ==> parallel

# determinan
#### for singular 
[a b  
 c d]

 if this matirx is singlar we have:

 (a+b)*k=(c+d) --->  ak=c , bk=d 

 like 
 [1 2  
        2 4]

then k=2.

c/a=d/b=k ---> ad-bc=0 

##### so for singular matrix determinan is zero

In [3]:
import numpy as np
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [4]:
np.vstack([a1,a2])

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [5]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [6]:
from sympy import Matrix 

A1 = Matrix([[8, 4, 26000],
            [3, 1, 10000]])
A1.rref()

ModuleNotFoundError: No module named 'sympy'

In [11]:
A1 = np.array([[7, 4],
            [3, 1]])
b=np.array([[26000],[10000]])
np.linalg.solve(A1,b)

array([[2800.],
       [1600.]])

In [13]:
np.linalg.det([[4,-3],[7,-8]])

-10.999999999999996