# Singular or non singular

1. non_singular ---> (x+y=5)(,x+2y=6)--> y=1,x=4 ==> unique solution
2. singular and redundant ---> (x+y=2),(2x+2y=4)---> many solutions
3. singular and contradiction ---> (x+y=5),(x+y=10)---> !!! no solution ==> parallel

# determinan
#### for singular 
[a b  
 c d]

 if this matirx is singlar we have:

 (a+b)*k=(c+d) --->  ak=c , bk=d 

 like 
 [1 2  
        2 4]

then k=2.

c/a=d/b=k ---> ad-bc=0 

##### so for singular matrix determinan is zero

In [3]:
import numpy as np
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [4]:
np.vstack([a1,a2])

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [5]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [6]:
A1 = np.array([[7, 4],
            [3, 1]])
b=np.array([[26000],[10000]])
np.linalg.solve(A1,b)

array([[2800.],
       [1600.]])

np.linalg.det([[4,-3],[7,-8]])

In [9]:
a=np.array([[7,5,3],[3,2,5],[1,2,1]])
b=np.array([[120],[70],[20]])
np.linalg.solve(a,b)

array([[15.],
       [ 0.],
       [ 5.]])

In [11]:
v = np.array([[1],[3]])
v

array([[1],
       [3]])

## dot product

#### L1 norm 
u=ai,v=bj ==>|L1|=|a|+|b|

#### L2 norm

|L2|=np.sqrt(a**2+b**2)

#### dot product
u=ai+bj
|L2|=np.sqrt(np.dot(u,u))



In [12]:
print("Norm of a vector v is", np.linalg.norm(v))

3.1622776601683795

In [14]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)
def dot(x, y):
    s=0
    for xi, yi in zip(x, y):
        s += xi * yi
    return s

In [15]:
import time

tic = time.time()
c = dot(a,b)
toc = time.time()
print("Dot product: ", c)
print ("Time for the loop version:" + str(1000*(toc-tic)) + " ms")

Dot product:  250031.35663301378
Time for the loop version:257.5998306274414 ms


In [16]:
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print("Dot product: ", c)
print ("Time for the vectorized version, np.dot() function: " + str(1000*(toc-tic)) + " ms")

Dot product:  250031.35663301378
Time for the vectorized version, np.dot() function: 4.378795623779297 ms


In [17]:
tic = time.time()
c = a @ b
toc = time.time()
print("Dot product: ", c)
print ("Time for the vectorized version, @ function: " + str(1000*(toc-tic)) + " ms")

Dot product:  250031.35663301378
Time for the vectorized version, @ function: 2.183675765991211 ms


##### You can see that vectorization is extremely beneficial in terms of the speed of calculations!

### Application of the Dot Product: Vector Similarity
Geometric definition of a dot product is used in one of the applications - to evaluate vector similarity. In Natural Language Processing (NLP) words or phrases from vocabulary are mapped to a corresponding vector of real numbers. Similarity between two vectors can be defined as a cosine of the angle between them. When they point in the same direction, their similarity is 1 and it decreases with the increase of the angle.

Then equation  (2)
  can be rearranged to evaluate cosine of the angle between vectors:

cos(𝜃)=𝑥⋅𝑦|𝑥||𝑦|.(3)
Zero value corresponds to the zero similarity between vectors (and words corresponding to those vectors). Largest value is when vectors point in the same direction, lowest value is when vectors point in the opposite directions.

This example of vector similarity is given to link the material with the Machine Learning applications. There will be no actual implementation of it in this Course. Some examples of implementation can be found in the Natual Language Processing Specialization.

Well done, you have finished this lab!

<a name='2'></a>
## 2 - Matrix Multiplication using Python

Like with the dot product, there are a few ways to perform matrix multiplication in Python. As discussed in the previous lab, the calculations are more efficient in the vectorized form. Let's discuss the most commonly used functions in the vectorized form. First, define two matrices:

In [18]:
A = np.array([[4, 9, 9], [9, 1, 6], [9, 2, 3]])
print("Matrix A (3 by 3):\n", A)

B = np.array([[2, 2], [5, 7], [4, 4]])
print("Matrix B (3 by 2):\n", B)

Matrix A (3 by 3):
 [[4 9 9]
 [9 1 6]
 [9 2 3]]
Matrix B (3 by 2):
 [[2 2]
 [5 7]
 [4 4]]


In [19]:
np.matmul(A, B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [20]:
A @ B

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [21]:
np.dot(A, B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

Yes, it works! What actually happens is what is called **broadcasting** in Python: `NumPy` broadcasts this dot product operation to all rows and all columns, you get the resultant product matrix. Broadcasting also works in other cases, for example:

In [22]:
np.multiply(A,B)

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

##  Transformations Defined as a Matrix Multiplication
<a name='3'></a>

Let $L: \mathbb{R}^m \rightarrow \mathbb{R}^n$ be defined by a matrix $A$, where $L(v)=Av$, multiplication of the matrix $A$ ($n\times m$) and vector $v$ ($m\times 1$) resulting in the vector $w$ ($n\times 1$).

Now try to guess, what should be the elements of matrix $A$, corresponding to the transformation $L: \mathbb{R}^2 \rightarrow \mathbb{R}^3$:

$$L\begin{pmatrix}
          \begin{bmatrix}
           v_1 \\           
           v_2
          \end{bmatrix}\end{pmatrix}=
          \begin{bmatrix}
           3v_1 \\
           0 \\
           -2v_2
          \end{bmatrix}=
          \begin{bmatrix}
           ? & ? \\
           ? & ? \\
           ? & ?
          \end{bmatrix}
          \begin{bmatrix}
           v_1 \\
           v_2
          \end{bmatrix}
          \tag{4}
          $$

To do that, write the transformation $L$ as $Av$ and then perform matrix multiplication:
    $$L\begin{pmatrix}
          \begin{bmatrix}
           v_1 \\           
           v_2
          \end{bmatrix}\end{pmatrix}=
          A\begin{bmatrix}
           v_1 \\           
           v_2
          \end{bmatrix}=
          \begin{bmatrix}
           a_{1,1} & a_{1,2} \\
           a_{2,1} & a_{2,2} \\
           a_{3,1} & a_{3,2}
          \end{bmatrix}
          \begin{bmatrix}
           v_1 \\           
           v_2
          \end{bmatrix}=
          \begin{bmatrix}
           a_{1,1}v_1+a_{1,2}v_2 \\
           a_{2,1}v_1+a_{2,2}v_2 \\
           a_{3,1}v_1+a_{3,2}v_2 \\
          \end{bmatrix}=
          \begin{bmatrix}
           3v_1 \\
           0 \\
           -2v_2
          \end{bmatrix}\tag{5}
          $$
          
Can you see now what should be the values of the elements $a_{i,j}$ of matrix $A$ to make the equalities $(5)$ correct? Find out the answer in the following code cell:

In [24]:
def L(v):
    A = np.array([[3,0], [0,0], [0,-2]])
    print("Transformation matrix:\n", A, "\n")
    w = A @ v
    
    return w

v = np.array([[3], [5]])
w = L(v)

print("Original vector:\n", v, "\n\n Result of the transformation:\n", w)

Transformation matrix:
 [[ 3  0]
 [ 0  0]
 [ 0 -2]] 

Original vector:
 [[3]
 [5]] 

 Result of the transformation:
 [[  9]
 [  0]
 [-10]]


Every linear transformation can be carried out by matrix multiplication. And vice versa, carrying out matrix multiplication, it is natural to consider the linear transformation that it represents. It means you can associate the matrix with the linear transformation in some way. This is a key connection between linear transformations and matrix algebra.

In [25]:
A = np.array([[1,2,-1], [1,0,1], [0,1,0]])

np.linalg.inv(A)

array([[ 0.5,  0.5, -1. ],
       [ 0. ,  0. ,  1. ],
       [-0.5,  0.5,  1. ]])

In [27]:
v = np.array([[5], [-2],[0]])
A@v

array([[ 1],
       [ 5],
       [-2]])